version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: production
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./env/production.env
    volumes:
      - static_volume:/app/static/
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/app/static/
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: carmarket
      POSTGRES_USER: caruser
      POSTGRES_PASSWORD: carpass
    volumes:
      - postgres_prod:/var/lib/postgresql/data/

volumes:
  static_volume:
  postgres_prod:
